name: Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  schedule:
    - cron: "5 7 */9 * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: boidolr/actions/python-pip-env@main
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Execute tests
        run: |
          pip3 install -q tox
          tox -e py

  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: boidolr/actions/run-precommit@main
