name: "pre-commit update"
on:
  workflow_dispatch:
  schedule:
    - cron: "5 7 */7 * *"

permissions:
  contents: write

jobs:
  pre-commit-update:
    runs-on: ubuntu-latest
    env:
      BRANCH: main

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: boidolr/actions/run-precommit@main
        with:
          autoupdate: true

      - name: Push pre-commit changes
        uses: boidolr/actions/git-push@main
        with:
          message: "Update pre-commit config"
          branch: "${{ env.BRANCH }}"
